#!/usr/bin/env bash
# ============================================================
# publish-baseera.sh
# Called by Cowork after a Baseera edition is completed.
# Creates a new content file, commits it to a branch,
# and opens a GitHub PR for Muhammad to review before deploy.
#
# Usage:
#   ./scripts/publish-baseera.sh \
#     --edition 2 \
#     --title "When Systems Fail People" \
#     --date "2025-02-01" \
#     --article "Article Title Here" \
#     --article-url "https://example.com" \
#     --author "Author Name" \
#     --finding "The key finding from the article." \
#     --pattern "The cross-sector pattern Muhammad identified." \
#     --signal "The actionable so-what for leaders." \
#     --tags "AI,Systems Thinking,Healthcare" \
#     --linkedin-url "https://linkedin.com/posts/..." \
#     --content-file "/path/to/full-content.md"
# ============================================================

set -euo pipefail

# --- Parse arguments ---
EDITION=""
TITLE=""
DATE="$(date +%Y-%m-%d)"
ARTICLE=""
ARTICLE_URL=""
AUTHOR=""
FINDING=""
PATTERN=""
SIGNAL=""
TAGS=""
LINKEDIN_URL=""
CONTENT_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --edition)       EDITION="$2";       shift 2 ;;
    --title)         TITLE="$2";         shift 2 ;;
    --date)          DATE="$2";          shift 2 ;;
    --article)       ARTICLE="$2";       shift 2 ;;
    --article-url)   ARTICLE_URL="$2";   shift 2 ;;
    --author)        AUTHOR="$2";        shift 2 ;;
    --finding)       FINDING="$2";       shift 2 ;;
    --pattern)       PATTERN="$2";       shift 2 ;;
    --signal)        SIGNAL="$2";        shift 2 ;;
    --tags)          TAGS="$2";          shift 2 ;;
    --linkedin-url)  LINKEDIN_URL="$2";  shift 2 ;;
    --content-file)  CONTENT_FILE="$2";  shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

# --- Validate required args ---
if [[ -z "$EDITION" || -z "$TITLE" || -z "$FINDING" || -z "$PATTERN" || -z "$SIGNAL" ]]; then
  echo "❌  Missing required arguments. Need: --edition, --title, --finding, --pattern, --signal"
  exit 1
fi

# --- Slugify title ---
SLUG="edition-$(printf '%03d' "$EDITION")"
BRANCH="baseera/edition-${EDITION}"
FILEPATH="src/content/baseera/${SLUG}.md"

echo "🚀  Publishing Baseera Edition ${EDITION}: ${TITLE}"

# --- Ensure we're on main and up to date ---
git checkout main
git pull origin main

# --- Create branch ---
git checkout -b "$BRANCH"

# --- Format tags as YAML array ---
TAGS_YAML=""
if [[ -n "$TAGS" ]]; then
  IFS=',' read -ra TAG_ARR <<< "$TAGS"
  TAGS_YAML="tags:"$'\n'
  for tag in "${TAG_ARR[@]}"; do
    tag="${tag#"${tag%%[![:space:]]*}"}"  # trim leading whitespace
    TAGS_YAML+="  - \"${tag}\""$'\n'
  done
fi

# --- Write frontmatter ---
cat > "$FILEPATH" << FRONTMATTER
---
title: "${TITLE}"
edition: ${EDITION}
date: "${DATE}"
article: "${ARTICLE}"
$([ -n "$ARTICLE_URL" ] && echo "articleUrl: \"${ARTICLE_URL}\"")
$([ -n "$AUTHOR" ] && echo "author: \"${AUTHOR}\"")
finding: "${FINDING}"
pattern: "${PATTERN}"
signal: "${SIGNAL}"
${TAGS_YAML}$([ -n "$LINKEDIN_URL" ] && echo "linkedinUrl: \"${LINKEDIN_URL}\"")
---

FRONTMATTER

# --- Append full content if provided ---
if [[ -n "$CONTENT_FILE" && -f "$CONTENT_FILE" ]]; then
  cat "$CONTENT_FILE" >> "$FILEPATH"
  echo "" >> "$FILEPATH"
fi

# --- Git commit ---
git add "$FILEPATH"
git commit -m "feat(baseera): add Edition ${EDITION} — ${TITLE}"

# --- Push branch ---
git push origin "$BRANCH"

# --- Open PR ---
PR_URL=$(gh pr create \
  --title "Baseera Edition ${EDITION}: ${TITLE}" \
  --body "## Baseera Edition ${EDITION}

**${TITLE}**

**The Finding:** ${FINDING}

**The Pattern:** ${PATTERN}

**The Signal:** ${SIGNAL}

---

### To publish:
1. Review the content in \`${FILEPATH}\`
2. If it looks good, merge this PR
3. Vercel will auto-deploy in ~60 seconds
4. The edition will appear live at [mseedat.co/baseera/${SLUG}](https://mseedat.co/baseera/${SLUG})

*Generated by Cowork Baseera automation*" \
  --base main \
  --head "$BRANCH")

echo ""
echo "✅  Done! PR opened:"
echo "   ${PR_URL}"
echo ""
echo "   Review + merge to publish Edition ${EDITION} to mseedat.co"
